

# Rabit MQ

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-Money
  labels:
    app: rmq-Money
spec:
  selector:
    matchLabels:
      app: rmq-Money
  replicas: 1
  template:
    metadata:
      labels:
        app: rmq-Money
    spec:
      containers:
      - name: rmq-Money
        image: rabbitmq
        ports:
        - name: rmq-Money-port
          containerPort: 15672
          imagePullPolicy: Always
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"


