apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingService-api-deployment
  labels:
    app: billing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing-api
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/billing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
#The port the container will expose to the network

# emailService App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailService-api-deployment
  labels:
    app: email-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
      - name: email-api
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/email:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002


# paymentService App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentService-api-deployment
  labels:
    app: payment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/payment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003


# userService App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userService-api-deployment
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004


# walletService App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: walletService-api-deployment
  labels:
    app: wallet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
    spec:
      containers:
      - name: wallet-api
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/wallet:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005


# Rabit MQ

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-Money
  labels:
    app: rmq-Money
spec:
  selector:
    matchLabels:
      app: rmq-Money
  replicas: 1
  template:
    metadata:
      labels:
        app: rmq-Money
    spec:
      containers:
      - name: rmq-Money
        image: rabbitmq
        ports:
        - name: rmq-Money-port
          containerPort: 15672
          imagePullPolicy: Always
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"


