apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: default
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::178933473620:user/ECR_user
      username: ECR_user
      groups:
        - system:masters
        
        
        
