apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  labels:
    app: billing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/billing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        
        
   apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: billing
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/email:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        
  

        
        
       
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: billing
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/payment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        
        
