apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  selector:
    matchLabels:
      app: billing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/billing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
       
       
       
---


kind: Deployment
apiVersion: apps/v1
metadata:
  name: email
spec:
  selector:
    matchLabels:
      app: email
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/email:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002

