apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  selector:
    matchLabels:
      app: billing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/billing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
       

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: email
spec:
  selector:
    matchLabels:
      app: email
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/email:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
 


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/payment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
       


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
       


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: wallet
spec:
  selector:
    matchLabels:
      app: wallet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
      - name: wallet
        image: 178933473620.dkr.ecr.us-east-2.amazonaws.com/wallet:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        
        
 
