# email Service service file

apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  ports:
  - port: 3001
    targetPort: billing-port
    protocol: TCP
  selector:
    app: billing
  type: NodePort
  

---

kind: Service
apiVersion: v1
metadata:
  name: email-service
spec:
  ports:
  - port: 3002
    targetPort: email-port
    protocol: TCP
  selector:
    app: email
  type: ClusterIP

