# email Service service file

apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  ports:
  - port: 3001
    targetPort: billing-port
    protocol: TCP
  selector:
    app: billing
  type: NodePort
  


