name

on:
  push:
    branches:
      - main

    paths:
      - "money-pal/billingService/**"
      - ".github/workflows/billingservice.yml"


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Install Node.js dependencies
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test

      # Login to Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: enricay/billing:latest
