name: billingService Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    paths:
      - "money-pal/billingService/**"
      - ".github/workflows/billingservice.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./billingService

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: ./billingService/package-lock.json
    - name: Install Dependencies
      run: npm install
    - name: Test
      run: npm test
