name: clientApp Deploy

# Controls when the action will run. 
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# Triggers the workflow on push or pull request events but only for when there's changes in this path.
    paths:
      - "money-pal/clientApp/**"
      - ".github/workflows/client.yml"

# We declare multiple jos that runs sequentially.
jobs:
  deploy-clientApp-to-s3:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./clientApp/
    
    
    steps:
# Checks-out ther repository under $GITHUB_WORKSPACE, so this job can access it
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
#        cache: 'npm'
#        cache-dependency-path: ./clientApp/package-lock.json
        
# install applicaion dependencies
    - name: Install Dependencies
      run: |
        npm install
        
# build and test the apps 
    - name: NPM build Angular
      run: npm run build
    
                
# Deploy to S3
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
          # --acl public read => makes files publicly readable(i.e. makes sure that your bucket settings are also set to public)
          # --delete => permanently deletes files in S3 bucket that are not present in latest build
        args: --acl public-read --follow-symlinks --delete  
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: './build'
