name: billingService Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    paths:
      - 'billingService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        cache: 'npm'
        cache-dependency-path: billingService/package-lock.json
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
