name: Monie-pal CI

on:
  push:
    branches: 
      - master

    paths:
      - 'billingService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
          cache-dependency-path: billingService/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test




name: Monie-pal Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    paths:
      - 'billingService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.x'
        cache: 'npm'
        cache-dependency-path: billingService/package-lock.json
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
