name: Monie-pal Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
        cache-dependency-path: subdir/package-lock.json
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
