name: Monie-pal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
          cache: "npm"
          cache-dependency-path: service/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
